/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './common/components/**/*.{js,vue,ts}',
    './common/layouts/**/*.{js,vue,ts}',
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    colors: {
      'primary': '#005862',
      'primary-light-1': '#337981',
      'primary-light-2': '#669BA1',
      'primary-light-3': '#99BCC0',
      'primary-light-4': '#CCDEE0',
      'primary-light-5': '#F2F6F7',
      'primary-light-6': '#F0F7F5',
      'primary-dark-1': '#004F58',
      'primary-dark-2': '#00474F',
      'primary-dark-3': '#004047',
      'primary-dark-4': '#003A40',
      white: '#FFFFFF',
      black: '#292929',
      red: '#EF5149',
      'red-1': '#FEEDED',
      'red-light-1': '#F2746D',
      'red-light-2': '#F59792',
      'red-light-3': '#F9B9B6',
      'red-light-4': '#FCDCDB',
      'red-dark-1': '#D74942',
      'red-dark-2': '#D74942',
      'red-dark-3': '#AE3B35',
      'red-dark-4': '#9D3530',
      blue: '#499FEF',
      'blue-1': '#EDF6FE',
      'blue-2': '#25C4E7',
      'blue-3': '#EDFBFE',
      orange: '#EF9949',
      'orange-1': '#FEF5ED',
      'orange-2': '#EF4949',
      'orange-3': '#FFF6ED',
      'orange-4': '#FFA149',
      green: '#49EF9F',
      'green-1': '#EDFEF6',
      'green-2': '#02CD6B',
      'gray-dark': '#797777',
      gray: '#AAAAAA',
      'gray-1': '#656565',
      'gray-light': '#E2E2E2',
      'gray-light-1': '#F5F5F5',
    },
    extend: {
      fontFamily: {},
      spacing: {
        1: '4px',
        2: '8px',
        2.5: '11px',
        3: '12px',
        4: '16px',
        5: '24px',
        6: '32px',
        7: '40px',
        8: '48px',
      },
      fontSize: {
        xs: '12px',
        sm: '14px',
        base: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '32px',
        '3xl': '40px',
      },
      lineHeight: {
        1: '18px',
        2: '21px',
        3: '24px',
        4: '27px',
        5: '30px',
        6: '48px',
        7: '60px',
      },
      backgroundImage: {
        'bg-home-page': "url('/img/hero-pattern.svg')",
      },
      flex: {
        '1-auto': '1 0 auto',
        '0-auto': '0 0 auto'
      },
    },
  },
  plugins: [],
}
